showVerionsTab: true
showEnvVarsTab: false
useRawYaml: false
allowAutoApplyLimits: false
name: Ingress
title: Ingress
logo: AppstoreAddOutlined
tags:
  - Ingress
  - DevOps
description: Ingress
oneDeploymentPerCluster: true
notAllowRemoveNamespace: false
